### ISSUE TITLE
Investigate test failure on node 8

### ISSUE THREAD

**Issue by vweevers** [prebuild/prebuildify#38]
https://travis-ci.org/github/prebuild/prebuildify/jobs/681902103
https://travis-ci.org/github/prebuild/prebuildify/jobs/681901064

```
# prefers locally installed node-gyp bin
C:\Users\travis\build\prebuild\prebuildify\test\mock-gyp>if not defined npm_config_node_gyp (node "C:\ProgramData\nvs\node\8.17.0\x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --target=v8.17.0 --devdir=C:\Users\travis\AppData\Local\Temp\prebuildify\node --target_arch=x64 --release )  else (node "C:\ProgramData\nvs\node\8.17.0\x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --target=v8.17.0 --devdir=C:\Users\travis\AppData\Local\Temp\prebuildify\node --target_arch=x64 --release ) 
not ok 7 should be equal
  ---
    operator: equal
    expected: |-
      'node-gyp exited with 123'
    actual: |-
      'node-gyp exited with 1'
    at: ChildProcess.<anonymous> (C:\Users\travis\build\prebuild\prebuildify\index.js:209:24)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (C:\Users\travis\build\prebuild\prebuildify\node_modules\tape\lib\test.js:228:54)
          at Test.bound [as _assert] (C:\Users\travis\build\prebuild\prebuildify\node_modules\tape\lib\test.js:80:32)
          at Test.equal (C:\Users\travis\build\prebuild\prebuildify\node_modules\tape\lib\test.js:389:10)
          at Test.bound [as is] (C:\Users\travis\build\prebuild\prebuildify\node_modules\tape\lib\test.js:80:32)
          at C:\Users\travis\build\prebuild\prebuildify\test\api.js:52:7
          at C:\Users\travis\build\prebuild\prebuildify\index.js:70:23
          at C:\Users\travis\build\prebuild\prebuildify\index.js:86:23
          at ChildProcess.<anonymous> (C:\Users\travis\build\prebuild\prebuildify\index.js:209:24)
          at emitTwo (events.js:126:13)
          at ChildProcess.emit (events.js:214:7)
```

**Comment by ralphtheninja** [comment]
Is the error code really important?

**Comment by vweevers** [comment]
123 is from a (mock) locally installed node-gyp, 1 is from npm-bundled node-gyp.

We could just drop node 8.

**Comment by vweevers** [comment]
I cannot reproduce locally. Disabled the test on node 8.
