### ISSUE TITLE
Addon compiled by `prebuildify` does not work, but the one compiled by node-gyp-build does

### ISSUE THREAD

**Issue by NoahAndrews** [prebuild/prebuildify#71]
I'm seeing this behavior on [this project](https://github.com/REVrobotics/node-can-bridge). I can reproduce this all on a single Windows machine. Everything should be 64-bit (including my node.js installation), and the addon uses NAPI, so there should not be a platform mismatch.

### Reproduction steps:
1. `git clone https://github.com/REVrobotics/node-can-bridge`
2. `cd node-can-bridge`
3. `git checkout v2.0.5`
4. `npm install`
5. `npm run prepublishOnly` (runs prebuildify)
6. `npm install --verbose`

When you run `npm install --verbose`, `node-gyp-build` sees the prebuilt addon that was built in the previous step, but it prints the following error and goes on to rebuild the addon.

```
node:internal/modules/cjs/loader:1280
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Users\Noah\node-can-bridge\prebuilds\win32-x64\node.napi.node is not a valid Win32 application.
\\?\C:\Users\Noah\node-can-bridge\prebuilds\win32-x64\node.napi.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1280:18)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at load (C:\Users\Noah\node-can-bridge\node_modules\node-gyp-build\node-gyp-build.js:22:10)
    at Object.<anonymous> (C:\Users\Noah\node-can-bridge\node_modules\node-gyp-build\build-test.js:19:19)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

I'd appreciate any guidance for debugging this. While it's good that at least the rebuild is working correctly, it would be nice to get to the bottom of this.

**Comment by NoahAndrews** [comment]
It actually has something to do with one of the DLL files that I had set up to be placed in `prebuilds`, but not the `node-gyp-build` Release folder. I get the same behavior on the fresh build if I copy the DLLs over.
